# Generated by Django 5.0.2 on 2024-03-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertask',
            old_name='taskId',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='usertask',
            old_name='userId',
            new_name='user',
        ),
        migrations.AddField(
            model_name='usertask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodule',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In-progress', 'In-progress'), ('Not-started', 'Not-started')], max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100),
        ),
    ]
