# Generated by Django 5.0.2 on 2024-03-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_taskid_usertask_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In-progress', 'In-progress'), ('Not-started', 'Not-started')], null=True),
        ),
    ]
