# Generated by Django 5.0.2 on 2024-03-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In-progress', 'In-progress'), ('Not-started', 'Not-started')], max_length=100, null=True),
        ),
    ]
